/** Gemeinsame Styles für primäre CTAs (Login, Onboarding) — wie Button-Variante `gold` (DESIGN.md v3.2). */
export const glassPrimaryButtonProps = {
  variant: "unstyled" as const,
  display: "flex" as const,
  alignItems: "center" as const,
  justifyContent: "center" as const,
  minH: "44px",
  w: "full",
  fontWeight: "600",
  fontSize: "md",
  borderRadius: "8px",
  color: "var(--cc-on-gold)",
  bg: "var(--cc-gold)",
  bgImage: "var(--cc-gold-grad)",
  boxShadow: "0 6px 18px rgba(212, 176, 128, 0.22), inset 0 1px 0 rgba(255, 255, 255, 0.35)",
  transition: "transform 180ms var(--cc-ease), box-shadow 180ms var(--cc-ease), filter 180ms var(--cc-ease)",
  _hover: {
    filter: "brightness(1.06)",
    transform: "translateY(-1px)",
    boxShadow: "0 0 26px rgba(212, 176, 128, 0.45), inset 0 1px 0 rgba(255, 255, 255, 0.4)",
  },
  _active: {
    transform: "translateY(0)",
    filter: "brightness(0.96)",
  },
  _disabled: {
    opacity: 1,
    bg: "rgba(255, 255, 255, 0.06)",
    bgImage: "none",
    boxShadow: "none",
    color: "rgba(255, 255, 255, 0.35)",
    cursor: "not-allowed",
    transform: "none",
    filter: "none",
  },
};
